### PR TITLE
Add `GroqLLM` integration

### LINKED ISSUE #348: [FEATURE] Thinking of adding a GroqLLM integration to distilabel
[Groq](https://wow.groq.com/why-groq/) is a startup developing LPU engines which provide 18x faster inference than GPUs. They currently provide Llama2-70B via API, and Mixtral 8x7B access on request. It would be great to add a `GroqLLM` module to distilabel just like we have `OpenAILLM`. I've been trying out their platform and it's 🔥 . 

It shouldn't be too difficult because they already try to make switching from OpenAI to Groq API easy.

### PR DESCRIPTION
**Pull request by kcentric**
Closes #348.

This PR adds `groq` as a new module in `distilabel.llm`, as an integration for the [Groq API](https://wow.groq.com/). Groq provides access to Llama2-70B and Mixtral 8x7B models running on an LPU engine, with inference speed up to 18x faster than regular GPUs.

Because Groq tries to make it easy to transfer from OpenAI API to their API, GroqLLM is structured in a similar way to `OpenAILLM`.

I have:
- Added [Groq](https://pypi.org/project/groq/) as an optional dependency to [pyproject.toml](https://github.com/kcentric/distilabel/blob/main/pyproject.toml).
- Added _GROQ_AVAILABLE check to [imports.py](https://github.com/kcentric/distilabel/blob/main/src/distilabel/utils/imports.py).
- Completed basic GroqLLM class. Left #TODO notes to double-check whether Groq supports a few things that OpenAI does, but current code should be functional. I hope to be approved for Groq's alpha release soon so I can test it out and create a basic tutorial demonsrating how to use GroqLLM.

Need to:
- Add a section in [distilabel docs](https://distilabel.argilla.io/latest/) specifying that Groq is available as an extra.
- Add a [tutorial](https://distilabel.argilla.io/latest/tutorials/pipeline-notus-instructions-preferences-legal/) that uses GroqLLM. This first requires Groq access.

### CODE REVIEW

**Comment by plaguss** [comment]
Hi @kcentric, thanks for the PR, it's awesome! Haven't tested it, but looks really nice. We are currently doing a refactor that would affect the way the `LLMs` are defined in `distilabel`, and this will need some modifications. Let's keep this PR as a guide for the moment

**Comment by alvarobartt** [comment]
Hi @kcentric thanks for the PR, awesome job! I guess you still need to clarify some things and tackle some TODOs so no worries, we won't merge until you let us know it's finished!

Also to confirm to @plaguss I told him we can merge that within the `main` branch and then we adapt it ourselves to the refactor, so that the PR is not left stale, so we can have it as a reference within the `main` branch, so that anyone can still use it when installing from source 👍🏻

**Comment by kcentric** [comment]
Thanks guys! @plaguss @alvarobartt I did hear that `distilabel` is undergoing refactoring, so yes I'm sure we can modify the LLM definition later. The `Groq` code here should work based off the current version of distilabel already. We just need to verify it live by trying it out in a Colab notebook. 

@alvarobartt I wonder how I should test whether `Groq` works? I'm waiting for Groq to approve me to access their API, but even so, if we haven't merged this PR by then, I won't be able to just do something like `from distilabel.llm import Groq`. How would I make sure everything's functional?

**Comment by alvarobartt** [comment]
Oh cool, thought you already tried the `GroqLLM` implementation and the official `Groq` client, but if that's not the case because you don't have access yet, then we can wait until you try it out, since the tests should be mocked, so those will work as long as everything's mocked properly.

**Comment by kcentric** [comment]
Yes, I'm still waiting on their early access approval. But if anyone else
has access to their API then is welcome to test it out.

I had tried their platform already because they were offering a UI
interface too.

**Comment by kcentric** [comment]
Hey guys, just an update: I still haven't got access to Groq API (a fact I don't really like, because I applied several weeks ago, but I think they have just way too many applicants). I'm wondering if you would like me to update the LLM code inside `Groq` to accommodate the new refactored `LLM` interface?
@plaguss @alvarobartt

**Comment by alvarobartt** [comment]
Hi @kcentric! Sure, if that's not too disruptive feel free to go ahead, but note that the base branch with the refactor is named `core-refactor` and some things may be still under documented, so maybe you can wait ~1 week? Otherwise, feel free to go ahead and drop us some feedback in the meantime!

**Comment by davidberenstein1957** [comment]
@kcentric If you want, there are a lot of open and closed PRs for the new `core-refactor` LLMs so you would be able to continue work on this :)

**Comment by kcentric** [comment]
@davidberenstein1957 Actually, I got access to Groq API beta a couple days ago after chatting with them a bit. I'm thinking to test this implementation then as soon as I have time. And then maybe we could merge this and anyone could refactor it later along with the other LLM modules, maybe.

**Comment by alvarobartt** [comment]
Sure @kcentric, feel free to continue with it on the current branch and we'll merge it, then we can take over and implement the refactored version ourselves! 👍🏻

**Comment by kcentric** [comment]
Also wondering @alvarobartt, since Groq is actually an API serving inference for several models, is it better to just a `GroqLLM` just like OpenAILLM, or rather have a `Groq Inference LLM` just like we have a `Together Inference LLM`?

Currently I set it up as GroqLLM because they've basically tried their best to make their API very OpenAI compatible. But just throwing the idea out there.

**Comment by kcentric** [comment]
Hey guys, I got GroqLLM working locally - fully integrated into `distilabel`. 🥳 I'm using PyCharm though, so I'm hoping to transfer the code to a notebook and be able to share.

**Comment by alvarobartt** [comment]
Hi here @kcentric, do you want me to take over this and refactor it in the latest version of `distilabel`? Or is that something you're planning to do by yourself? Thanks in advance! I'd like to see `QroqLLM` merged within the 1.1.0 release ⚡

**Comment by kcentric** [comment]
You can do it @Alvaro!

**Comment by alvarobartt** [comment]
> You can do it @alvaro!

Cool, thanks @kcentric, I'll make sure to credit you within the PR description 👍🏻

**Pull request closed without merging**
