### PR TITLE
Adds 01ai Client to Distillabel

### PR DESCRIPTION
**Pull request by Josephrp**
### [WIP] Adds 01ai Client to Distillabel

01ai recently released their 01ai API and it's serving `Yi-large` which is a great model for distillabel purposes.

### Open Tasks

- ~~[ ] Use Openai Async Client~~
- [x] add `Yi-large` default model
- [x] create tests
- ~~[ ] Create a Compatible Client (reach goal)~~
- [x] produce documentation
- [x] make examples
- [x] **(reach goal)** make a fun blog post

### CODE REVIEW

**Comment by Josephrp** [comment]
✨✨ Here's [an AI-assisted sketch of how you might approach this issue](https://copilot-workspace.githubnext.com/argilla-io/distilabel/pull/793?shareId=455fe1a3-9bee-4f5a-bae5-a530e869f800) saved by @Josephrp using Copilot Workspace v0.22

<details open><summary><b>Topic</b></summary>
<br/>

Use Openai Async Client

</details>

<details open><summary><b>Before</b></summary>
<br/>

- `src/distilabel/llms/openai.py` uses the OpenAI async client for generating responses.
- `OpenAILLM` class in `src/distilabel/llms/openai.py` implements the `agenerate` method for asynchronous generation.
- `OpenAILLM` class supports structured output using the `instructor` library.
- `OpenAILLM` class uses the `AsyncOpenAI` client for making API requests.
- `OpenAILLM` class handles various parameters like `max_new_tokens`, `temperature`, `top_p`, and `stop` for generation.
- `OpenAILLM` class can generate responses in both text and JSON formats.
- `OpenAILLM` class supports runtime parameters for `base_url`, `api_key`, `max_retries`, and `timeout`.

</details>
<details open><summary><b>After</b></summary>
<br/>

* `src/distilabel/llms/oneai.py` now uses the OpenAI async client for generating responses.
* `OneAI` class in `src/distilabel/llms/oneai.py` implements the `agenerate` method for asynchronous generation.
* `OneAI` class supports structured output using the `instructor` library.
* `OneAI` class uses the `AsyncOpenAI` client for making API requests.
* `OneAI` class handles various parameters like `max_new_tokens`, `temperature`, `top_p`, and `stop` for generation.
* `OneAI` class can generate responses in both text and JSON formats.
* `OneAI` class supports runtime parameters for `base_url`, `api_key`, `max_retries`, and `timeout`.


</details>

<details open><summary><b>Plan</b></summary>
<br/>

* `src/distilabel/llms/oneai.py` (CHANGE)
  - Implement the `OneAI` class using the OpenAI async client
  - Implement the `agenerate` method for asynchronous generation
  - Support structured output using the `instructor` library
  - Handle parameters like `max_new_tokens`, `temperature`, `top_p`, and `stop` for generation
  - Support runtime parameters for `base_url`, `api_key`, `max_retries`, and `timeout`
* `src/distilabel/llms/__init__.py` (CHANGE)
  - Import the `OneAI` class from `src/distilabel/llms/oneai.py`
  - Add `OneAI` to the `__all__` list
* `tests/unit/llms/test_openai.py` (CHANGE)
  - Add test cases for the `OneAI` class
  - Test the `agenerate` method for asynchronous generation
  - Test structured output using the `instructor` library
  - Test handling of parameters like `max_new_tokens`, `temperature`, `top_p`, and `stop` for generation
  - Test runtime parameters for `base_url`, `api_key`, `max_retries`, and `timeout`

</details>

<details open><summary><b>Sketch of implementation</b></summary>
<br/>

[View the changes](https://copilot-workspace.githubnext.com/argilla-io/distilabel/pull/793?shareId=455fe1a3-9bee-4f5a-bae5-a530e869f800)

<details open><summary><b>Details</b></summary>
<br/>

Code analyzed at ba6f71f75ad58a7aa2ef306813c7d1cd73e14002

</details>

**Comment by Josephrp** [comment]
big thanks to the maintainers for this cool new thing i discovered here called Github Workspace , it's amazing and very cool ! 👍🏻 🥇

**Comment by gabrielmbmb** [comment]
Thanks for the PR @Josephrp! If the 01.AI relies on the OpenAI client then maybe we can do like in the `AnyscaleLLM` or `TogetherLLM` in which we create a new class inheriting from `OpenAILLM`: https://github.com/argilla-io/distilabel/blob/main/src/distilabel/llms/anyscale.py

Did GitHub Copilot helped you with this PR? I haven't had the change to test it yet, looks cool :)

**Comment by Josephrp** [comment]
> Thanks for the PR @Josephrp! If the 01.AI relies on the OpenAI client then maybe we can do like in the `AnyscaleLLM` or `TogetherLLM` in which we create a new class inheriting from `OpenAILLM`: https://github.com/argilla-io/distilabel/blob/main/src/distilabel/llms/anyscale.py
> 
> Did GitHub Copilot helped you with this PR? I haven't had the change to test it yet, looks cool :)

yes ! thank you for the references , it's much appreciated and this method is obviously prefered , i'll do it like that to keep it simple :-)

just making a small NER model this weekend so i can make a little bit of docs and tuts using this one 💪🏻

**Comment by Josephrp** [comment]
i'll use it today and tomorrow to make NER and Embeddings training pipelines like what you have in tutorials, didnt really find a nice place to make a unique examples so i'll do the write ups separately.

**Comment by Josephrp** [comment]
🙋🏻‍♂️are there many breaking changes in the last two months i should be aware of ? @gabrielmbmb  :-)

**Comment by Josephrp** [comment]
01 ai YI api closed

**Pull request closed without merging**
