### PR TITLE
feat: add ETA to progress bar and fix not showing the progress bar if irrelavant

### LINKED ISSUE #243: [FEATURE] ETA for time until completion for progress bars
**Is your feature request related to a problem? Please describe.**
It would be nice to have an ETA for completion of the task when calling `pipeline. generate`.

**Describe the solution you'd like**
 At the moment, the progress bar gives an indication of progress, but it would be nice to also have an ETA of the time remaining. 

**Describe alternatives you've considered**
Being more patient... 

**Additional context**
I took a quick look, and since you are defining your own progress bar with Rich this might not be that easy to add.

### PR DESCRIPTION
**Pull request by ignacioct**
Closes #243 

Script for trying the progress bar

```python 

from distilabel.llm import InferenceEndpointsLLM
from distilabel.pipeline import Pipeline
from distilabel.tasks import TextGenerationTask

from datasets import Dataset

token = ""
model = "aws-notus-7b-v1-3184"
namespace = "argilla"

llm = InferenceEndpointsLLM(
    endpoint_name_or_model_id=model,  # type: ignore
    endpoint_namespace=namespace,  # type: ignore
    token=token,
    task=TextGenerationTask(),
)

pipeline = Pipeline(generator=llm)

inputs = ["Generate whatever"] * 50
dataset = Dataset.from_dict({"input": inputs})

generated_instructions = pipeline.generate(
    dataset=dataset, num_generations=1, display_progress_bar=True
)

print(generated_instructions[0])
```

With just this change, we obtain the following using the try script above:

```ssh

22:37:49 INFO     [PID: 48942] Processing batch 50 of 50...                                                                                 pipeline.py:567
         INFO     [PID: 48942] Calling generator for batch 50...                                                                            pipeline.py:571
Texts Generated ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 50/50 0:03:42
Rows labelled   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0%  0/50 -:--:--
Flattening the indices: 100%|████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 11395.09 examples/s]
Saving the dataset (1/1 shards): 100%|███████████████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 10768.98 examples/s]
```

Thanks @plaguss for all the doc, I owe you a beer! He was afraid that dealing with OpenAI's futures would break the progress, I still have to test that specifically.

### CODE REVIEW

**Review by davidberenstein1957 — COMMENTED** [review]
That is a quick and easy one haha. @ignacioct , if you want to tackle something else, feel free to pick something nice. Also, there is this tiny thing that you might have missed in the original issue? https://github.com/argilla-io/distilabel/issues/243#issuecomment-1892663702

In the example above, we also see the "Rows labelled".

**Comment by ignacioct** [comment]
@davidberenstein1957 ups, didn't see it! I fixed it in the last push, so everything should be working now.

**Comment by plaguss** [comment]
🍻 @ignacioct. Could you check a simple example with OpenAI to see if it renders properly? After that we should be ready to go

**Comment by ignacioct** [comment]
@plaguss do I need to set up an inference endpoint or is there a way to avoid that? I tried the model that the HF people used to test the serverless implementation, but it was giving me limit errors

**Comment by davidberenstein1957** [comment]
@ignacioct, I believe we can also only use a generator. Correct?

**Comment by plaguss** [comment]
we can use only the generator, but it would be nice to see if there is some problem with a complete pipeline, or at least a labelling pipeline using OpenAI. Does he have access to Open AI?

**Comment by davidberenstein1957** [comment]
@ignacioct there are some linting issues

**Pull request merged**
