### PR TITLE
feat: Fixing progress bar and ETA

### LINKED ISSUE #258: [FEATURE] Further changes on ETA for progress bars
There are still some additional changes to be done to the ETA for progress bars:

- [ ] Check OpenAI's future
- [ ] has_labeller and has_generator are not working

### PR DESCRIPTION
**Pull request by ignacioct**
Closes #258

### CODE REVIEW

**Comment by davidberenstein1957** [comment]
Thanks @ignacioct, it looks much cleaner.

**Comment by ignacioct** [comment]
> Thanks @ignacioct, it looks much cleaner.

@davidberenstein1957 Yes, was looking for a way of not initializing anything unnecessary. I'm still doing some tests, there are cases in which it does not show any ETA, just elapsed times at the end, and I'm unsure if it's my doing or the OpenAI's issue.

**Comment by davidberenstein1957** [comment]
I think it will compute the ETA based on leveraging out returned values and times in between so maybe your runs are too short to do a proper computation?

**Comment by ignacioct** [comment]
> @ignacioct I think it will compute the ETA based on leveraging out returned values and times in between so maybe your runs are too short to do a proper computation?

Could you share the script you used to test it? Thanks!

**Comment by davidberenstein1957** [comment]
I used the pipeline-llamacpp-and-openai.py and just replaced both LLMs with OpenAI ones :)

**Pull request merged**
