### PR TITLE
Remove Metadata for Ratings

### LINKED ISSUE #272: [FEATURE] Remove metadata for ratings
Thanks to the awesome work from @damianpumar we can now remove the "artificially" generated metadata properties for sorting by rank. This is handled automatically now in Argilla 🎉 (see https://github.com/argilla-io/argilla/releases/tag/v1.22.0)

image

We need to:

- Make sure to upgrade argilla dep to 1.22
- Remove all the rating metadata properties in to_argilla_dataset and to_argilla_records
- Test it works as expected
- We need to keep the best worse diff, which is still very useful
- For future issues: we could think of avg_rating that could help identify very low or very high overall ratings (all responses are very good or very bad)

### PR DESCRIPTION
**Pull request by ignacioct**
Closes #272

I haven't been able to find any other place in which the ratings metadata properties have been added, and I have tested with the SelfInstructTask. Can do further checking of each task individually if needed. Below, I've outputted the metadata properties of an instruction dataset after running the SelfInstruct

### CODE REVIEW

**Comment by ignacioct** [comment]
Metadata after running a SelfInstructTask:

```
[IntegerMetadataProperty(name='length-input', title='length-input', visible_for_annotators=True, type='integer', min=None, max=None),
 IntegerMetadataProperty(name='length-instruction', title='length-instruction', visible_for_annotators=True, type='integer', min=None, max=None),
 IntegerMetadataProperty(name='input_n_tokens', title='Input N Tokens', visible_for_annotators=True, type='integer', min=None, max=None),
 IntegerMetadataProperty(name='input_n_unique_tokens', title='Input N Unique Tokens', visible_for_annotators=True, type='integer', min=None, max=None),
 IntegerMetadataProperty(name='input_n_sentences', title='Input N Sentences', visible_for_annotators=True, type='integer', min=None, max=None),
 FloatMetadataProperty(name='input_perplexity', title='Input Perplexity', visible_for_annotators=True, type='float', min=None, max=None),
 FloatMetadataProperty(name='input_entropy', title='Input Entropy', visible_for_annotators=True, type='float', min=None, max=None),
 FloatMetadataProperty(name='input_flesch_reading_ease', title='Input Flesch Reading Ease', visible_for_annotators=True, type='float', min=None, max=None),
 IntegerMetadataProperty(name='instructions_n_tokens', title='Instructions N Tokens', visible_for_annotators=True, type='integer', min=None, max=None),
 IntegerMetadataProperty(name='instructions_n_unique_tokens', title='Instructions N Unique Tokens', visible_for_annotators=True, type='integer', min=None, max=None),
 IntegerMetadataProperty(name='instructions_n_sentences', title='Instructions N Sentences', visible_for_annotators=True, type='integer', min=None, max=None),
 FloatMetadataProperty(name='instructions_perplexity', title='Instructions Perplexity', visible_for_annotators=True, type='float', min=None, max=None),
 FloatMetadataProperty(name='instructions_entropy', title='Instructions Entropy', visible_for_annotators=True, type='float', min=None, max=None),
 FloatMetadataProperty(name='instructions_flesch_reading_ease', title='Instructions Flesch Reading Ease', visible_for_annotators=True, type='float', min=None, max=None)]
```

**Comment by plaguss** [comment]
Thanks @ignacioct! Could you review the `EvolInstruct` functionality too? 😄

**Comment by ignacioct** [comment]
> Thanks @ignacioct! Could you review the `EvolInstruct` functionality too? 😄

Do you mean that there can be rating metadata in EvolInstruct? @plaguss

**Comment by plaguss** [comment]
I think the code for the to_argilla methods is the same, didn't review it but maybe the same updates should be done there

**Comment by ignacioct** [comment]
@plaguss retried with an UltraCM task, and obtained these metadata properties:

```
[IntegerMetadataProperty(name='length-input', title='length-input', visible_for_annotators=True, type='integer', min=None, max=None),
 IntegerMetadataProperty(name='length-generations', title='length-generations', visible_for_annotators=True, type='integer', min=None, max=None),
 FloatMetadataProperty(name='distance-best-score', title='distance-best-score', visible_for_annotators=True, type='float', min=None, max=None),
 IntegerMetadataProperty(name='input_n_tokens', title='Input N Tokens', visible_for_annotators=True, type='integer', min=None, max=None),
 IntegerMetadataProperty(name='input_n_unique_tokens', title='Input N Unique Tokens', visible_for_annotators=True, type='integer', min=None, max=None),
 IntegerMetadataProperty(name='input_n_sentences', title='Input N Sentences', visible_for_annotators=True, type='integer', min=None, max=None),
 FloatMetadataProperty(name='input_perplexity', title='Input Perplexity', visible_for_annotators=True, type='float', min=None, max=None),
 FloatMetadataProperty(name='input_entropy', title='Input Entropy', visible_for_annotators=True, type='float', min=None, max=None),
 FloatMetadataProperty(name='input_flesch_reading_ease', title='Input Flesch Reading Ease', visible_for_annotators=True, type='float', min=None, max=None),
 IntegerMetadataProperty(name='generations_n_tokens', title='Generations N Tokens', visible_for_annotators=True, type='integer', min=None, max=None),
 IntegerMetadataProperty(name='generations_n_unique_tokens', title='Generations N Unique Tokens', visible_for_annotators=True, type='integer', min=None, max=None),
 IntegerMetadataProperty(name='generations_n_sentences', title='Generations N Sentences', visible_for_annotators=True, type='integer', min=None, max=None),
 FloatMetadataProperty(name='generations_perplexity', title='Generations Perplexity', visible_for_annotators=True, type='float', min=None, max=None),
 FloatMetadataProperty(name='generations_entropy', title='Generations Entropy', visible_for_annotators=True, type='float', min=None, max=None),
 FloatMetadataProperty(name='generations_flesch_reading_ease', title='Generations Flesch Reading Ease', visible_for_annotators=True, type='float', min=None, max=None)]
```

So I think we are good to go

**Review by plaguss — APPROVED** [review]

**Pull request merged**
