### PR TITLE
Add examples for the deita paper tasks

### PR DESCRIPTION
**Pull request by plaguss**
## Description

This PR includes additional examples and adds some notes for the Deita tasks.

### CODE REVIEW

**Review by davidberenstein1957 — COMMENTED** [review]
Hi @plaguss, I realized we return the rank/scores here but I'm not sure if this is handled intuitively because normally we work with ratings where a higher rating corresponds to a higher score but in this case, it is the other way around. Right? And this might not be aligned with the `RankingQuestion` in Argilla itself.

**Comment by plaguss** [comment]
Hi @davidberenstein1957, we don't really follow the paper strictly, we decided to interpret the scores as if those were `Ratings`, so we can reuse all the behaviour from the `PreferenceTask` without adding extra complexity for these tasks. This way, they are more reusable and we don't need to add a specific type of `Task` which takes into account the rankings. We should tackle this when we start integrating `PairRM` and such (this issue should take those into account: https://github.com/argilla-io/distilabel/issues/306). In this case the higher ratings are also higher scores too, higher complexity/quality corresponds to a better response.

The discussion from the PR can be seen [here](https://github.com/argilla-io/distilabel/pull/302).

**Comment by davidberenstein1957** [comment]
@plaguss I agree but now it seems like we attribute ratings to values that are originally rankings so they should be reversed to allow for choosing on of the preferred options. Correct?

rank 1, 2 => rating 2, 1 because a lower rating should translate in a higher rank?

**Comment by plaguss** [comment]
> @plaguss I agree but now it seems like we attribute ratings to values that are originally rankings so they should be reversed to allow for choosing on of the preferred options. Correct?
> 
> rank 1, 2 => rating 2, 1 because a lower rating should translate in a higher rank?
> 
> How is this handled in the to_argilla for example?

I understand, but for example, the `QualityScorer` uses the following prompt:
```python
from distilabel.tasks import QualityScorerTask

task = QualityScorerTask()
print(task.generate_prompt("What are the first 5 Fibonacci numbers?", ["0 1 1 2 3", "0 1 1 2 3"]).formatted_prompt)
```
```txt
Rank the following responses provided by different AI assistants to the user’s question
according to the quality of their response. Score each response from 1 to 2, with 3
reserved for responses that are already very well written and cannot be improved further.
Your evaluation should consider factors such as helpfulness, relevance, accuracy, depth,
creativity, and level of detail of the response.
Use the following format:
[Response 1] Score:
[Response 2] Score:
...
#Question#: What are the first 5 Fibonacci numbers?
#Response List#:

[Response 1] 0 1 1 2 3
[Response 2] 0 1 1 2 3
```

Maybe we can discuss whether the prompts really make sense in our case and maybe rewrite them to more more "inspired" from the deita paper, but just to represent proper ratings, explaining if lower/higher is worse/better

**Comment by davidberenstein1957** [comment]
@plaguss Yes it makes sense. I thought we needed to rank the responses within the prompt and that they were not directly asked to score. Ignore what I've commented above. 😅

**Pull request merged**
